### ISSUE TITLE
New 7 Days to Die EAC Update / Bypasses Broken

### ISSUE THREAD

**Issue by drpecker** [IntelSDM/7DTD#11]
Is it possible for you to make a new EAC bypass for 7d, for your tool or even sell it?

**Comment by IntelSDM** [comment]
This is Odd. I will check it out.

**Comment by IntelSDM** [comment]
Oh wow. They did create a patch for it.  Shocking that either they found this repo or someone linked it to them. I will have a look into bypassing it. You can still take nearly all of the code and use it on linux or gamepass.

**Comment by IntelSDM** [comment]
Alright, I bypassed in an record 4 minutes

**Comment by IntelSDM** [comment]
Since EAC is watching this repo its really not worth updating the bypass. There are only 4-5 servers on this game that even use EAC so bypassing it isn't exactly going to help you terrorize servers. 
If you really want to mess with those couple of EAC servers you can use Linux or gamepass. Its not worth it for me to burn bypasses. 
Setting it up on Linux is basically the same process. If I get bored and burnt out of a pretty big project I am doing right now then i will write a guide on how to use Linux to cheat on EAC. Its really not worth it to update the bypass though.

**Comment by drpecker** [comment]
Can I add you on discord and pay you for help? We have a tool, just don't know how to bypass, as the last bypass was patched. Again WILL PAY

**Comment by Rafa-smasher** [comment]
> Since EAC is watching this repo its really not worth updating the bypass. There are only 4-5 servers on this game that even use EAC so bypassing it isn't exactly going to help you terrorize servers. If you really want to mess with those couple of EAC servers you can use Linux or gamepass. Its not worth it for me to burn bypasses. Setting it up on Linux is basically the same process. If I get bored and burnt out of a pretty big project I am doing right now then i will write a guide on how to use Linux to cheat on EAC. Its really not worth it to update the bypass though.

Can u share the guide? plss

**Comment by IntelSDM** [comment]
> > Since EAC is watching this repo its really not worth updating the bypass. There are only 4-5 servers on this game that even use EAC so bypassing it isn't exactly going to help you terrorize servers. If you really want to mess with those couple of EAC servers you can use Linux or gamepass. Its not worth it for me to burn bypasses. Setting it up on Linux is basically the same process. If I get bored and burnt out of a pretty big project I am doing right now then i will write a guide on how to use Linux to cheat on EAC. Its really not worth it to update the bypass though.
> 
> Nice work dude Can u share the guide? plss

Sorry for the late response, I don't receive notifications on closed issues. If you want to get it to work without the effort of updating the way of file patching for Windows and you want to take a Linux approach it is quite simple. Follow my guide for [Unity Stealer](https://github.com/IntelSDM/UnityStealer/blob/master/Instructions.md). Instead of changing the file directory you can just directly do this to assembly-csharp.dll or any other main DLL.  Since DNSpy should still support Linux and if not you can just use Wine, it should be pretty easy to follow the guide.

**Comment by KeksikGh** [comment]
Hi!
Will you do a crawl for EAC or create a private\paid cheat for EAC servers?
