### ISSUE TITLE
help with creation

### ISSUE THREAD

**Issue by hesagoo** [IntelSDM/7DTD#6]
hello bro, I don't know much about code and I don't know how to use visual studio, could you describe or make a video in more detail on how to use this cheat. When I compile the assembly, it says 144 errors and 15 warnings and the dll file is not created...

**Comment by IntelSDM** [comment]
> hello bro, I don't know much about code and I don't know how to use visual studio, could you describe or make a video in more detail on how to use this cheat. When I compile the assembly, it says 144 errors and 15 warnings and the dll file is not created...

Sorry for the delayed reply. I have created a release branch here for you: 
https://github.com/IntelSDM/7DTD/releases/tag/Release
Most of those errors will be to do with game references to game dlls that haven't been included automatically on your machine, probably due to invalid file paths. This release build should work fine on your machine. Just follow the instructions in the release tab.
